name: build_push_slim_container

on:
  release:
    types:
      - created

jobs:
  docker-slim-build-container:
    name: Build and push container image to ECR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      -
        name: Tests
        run: |
          go mod tidy
          go test -v ./pkg/lambda
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
      -
        name: Get Tag Name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - 
        name: Login to GitHub Container registry
        uses: docker/login-action@v1
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push the Docker image
        run: |
          sudo curl https://downloads.dockerslim.com/releases/1.40.0/dist_linux.tar.gz -o ./dist_linux.tar.gz && sudo tar xf ./dist_linux.tar.gz -C . && sudo mv dist_linux/* /usr/bin && sudo chmod +x /usr/bin/docker-slim
          rm ./dist_linux.tar.gz
          docker-slim build --tag ghcr.io/martijnvdp/lambda-ecr-image-sync:$VERSION --tag ghcr.io/martijnvdp/lambda-ecr-image-sync:latest --tag ghcr.io/martijnvdp/lambda-ecr-image-sync:$VERSION --tag ghcr.io/martijnvdp/lambda-ecr-image-sync:latest --include-cert-all --http-probe=false --continue-after 60 --dockerfile ./Dockerfile --dockerfile-context . --delete-generated-fat-image
          docker push ghcr.io/martijnvdp/lambda-ecr-image-sync --all-tags
        shell: bash
        env:
          VERSION: ${{ steps.tag_name.outputs.SOURCE_TAG }}
